/* SPDX-License-Identifier: GPL-2.0 WITH Linux-syscall-note */
#ifndef _UAPI_LINUX_XPON_H
#define _UAPI_LINUX_XPON_H

#define XPON_GENL_NAME		"xpon"
#define XPON_GENL_VERSION	3

enum xpon_mode {
	XPON_MODE_GPON,
	XPON_MODE_EPON,
	XPON_MODE_XGSPON,

	__XPON_MODE_MAX,
};
#define XPON_MODE_MAX (__XPON_MODE_MAX - 1)

enum xpon_registration_state {
	XPON_REGISTRATION_DOWN,
	XPON_REGISTRATION_DISCOVERY,
	XPON_REGISTRATION_REGISTERING,
	XPON_REGISTRATION_OPERATIONAL,
};

/* Keep these values aligned with the generic optical frontend protocol IDs. */
enum xpon_optical_protocol {
	XPON_OPTICAL_PROTO_UNSPEC,
	XPON_OPTICAL_PROTO_ETHERNET,
	XPON_OPTICAL_PROTO_EPON,
	XPON_OPTICAL_PROTO_GPON,
	XPON_OPTICAL_PROTO_XGPON,
	XPON_OPTICAL_PROTO_XGSPON,
	XPON_OPTICAL_PROTO_NGPON2,
};

#define XPON_OPTICAL_CAP_TEMPERATURE	(1U << 0)
#define XPON_OPTICAL_CAP_VOLTAGE	(1U << 1)
#define XPON_OPTICAL_CAP_BIAS		(1U << 2)
#define XPON_OPTICAL_CAP_TX_POWER	(1U << 3)
#define XPON_OPTICAL_CAP_RX_POWER	(1U << 4)
#define XPON_OPTICAL_CAP_ALARMS		(1U << 5)
#define XPON_OPTICAL_CAP_TX_REARM	(1U << 6)
#define XPON_OPTICAL_CAP_TX_DISABLE	(1U << 7)
#define XPON_OPTICAL_CAP_TX_FAULT	(1U << 8)
#define XPON_OPTICAL_CAP_RX_LOS		(1U << 9)
#define XPON_OPTICAL_CAP_BURST_TX	(1U << 10)
#define XPON_OPTICAL_CAP_APD		(1U << 11)

#define XPON_OPTICAL_MODE_BURST_TX	(1U << 0)
#define XPON_OPTICAL_MODE_CONT_TX	(1U << 1)
#define XPON_OPTICAL_MODE_BURST_RX	(1U << 2)

enum xpon_optical_attr {
	XPON_OPTICAL_ATTR_UNSPEC,
	XPON_OPTICAL_ATTR_NAME,			/* string */
	XPON_OPTICAL_ATTR_TYPE,			/* string */
	XPON_OPTICAL_ATTR_VENDOR,		/* string */
	XPON_OPTICAL_ATTR_VENDOR_OUI,		/* binary, 3 bytes */
	XPON_OPTICAL_ATTR_PART_NUMBER,		/* string */
	XPON_OPTICAL_ATTR_SERIAL,		/* string */
	XPON_OPTICAL_ATTR_DATE_CODE,		/* string */
	XPON_OPTICAL_ATTR_CAPABILITIES,		/* u32, XPON_OPTICAL_CAP_* */
	XPON_OPTICAL_ATTR_PROTOCOLS,		/* u32, BIT(XPON_OPTICAL_PROTO_*) */
	XPON_OPTICAL_ATTR_PROTOCOL,		/* u8, enum xpon_optical_protocol */
	XPON_OPTICAL_ATTR_TX_RATE,		/* u64, bit/s */
	XPON_OPTICAL_ATTR_RX_RATE,		/* u64, bit/s */
	XPON_OPTICAL_ATTR_MODE_FLAGS,		/* u32, XPON_OPTICAL_MODE_* */
	XPON_OPTICAL_ATTR_PRESENT,		/* u8 */
	XPON_OPTICAL_ATTR_READY,		/* u8 */
	XPON_OPTICAL_ATTR_RX_LOS,		/* u8 */
	XPON_OPTICAL_ATTR_TX_FAULT,		/* u8 */
	XPON_OPTICAL_ATTR_TX_ENABLED,		/* u8 */
	XPON_OPTICAL_ATTR_TEMPERATURE_MC,	/* s32 */
	XPON_OPTICAL_ATTR_VOLTAGE_UV,		/* u32 */
	XPON_OPTICAL_ATTR_BIAS_UA,		/* u32 */
	XPON_OPTICAL_ATTR_TX_POWER_NW,		/* u32 */
	XPON_OPTICAL_ATTR_RX_POWER_NW,		/* u32 */
	XPON_OPTICAL_ATTR_ALARMS,		/* u32 */
	XPON_OPTICAL_ATTR_PAD,

	__XPON_OPTICAL_ATTR_MAX,
};
#define XPON_OPTICAL_ATTR_MAX (__XPON_OPTICAL_ATTR_MAX - 1)

enum xpon_oam_attr {
	XPON_OAM_ATTR_UNSPEC,
	XPON_OAM_ATTR_PRESENT,			/* u8, OAM provider registered */
	XPON_OAM_ATTR_ENABLED,			/* u8, administrative state */

	__XPON_OAM_ATTR_MAX,
};
#define XPON_OAM_ATTR_MAX (__XPON_OAM_ATTR_MAX - 1)

enum xpon_cmd {
	XPON_CMD_UNSPEC,
	XPON_CMD_GET,
	XPON_CMD_GET_CAPS,
	XPON_CMD_GET_STATE,
	XPON_CMD_SET_MODE,
	XPON_CMD_SET_OAM,
	XPON_CMD_EVENT,

	__XPON_CMD_MAX,
};
#define XPON_CMD_MAX (__XPON_CMD_MAX - 1)

enum xpon_attr {
	XPON_ATTR_UNSPEC,
	XPON_ATTR_IFINDEX,
	XPON_ATTR_MODE,
	XPON_ATTR_AVAILABLE_MODES,
	XPON_ATTR_REGISTRATION,
	XPON_ATTR_CARRIER,
	XPON_ATTR_SIGNAL_DETECT,
	XPON_ATTR_LOS,
	XPON_ATTR_CHANGED,
	XPON_ATTR_OPTICAL,			/* nested xpon_optical_attr */
	XPON_ATTR_OAM,				/* nested xpon_oam_attr */

	__XPON_ATTR_MAX,
};
#define XPON_ATTR_MAX (__XPON_ATTR_MAX - 1)

#endif /* _UAPI_LINUX_XPON_H */
